# Generated by Django 5.0.4 on 2025-09-18 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lang_type', models.CharField(choices=[('PY', 'PYTHON'), ('JS', 'JAVASCRIPT'), ('PHP', 'PHP'), ('CSS', 'CASCADING STYLE SHEET'), ('C++', 'C++')], default='PY', max_length=4)),
            ],
        ),
    ]
