# Generated by Django 5.2.6 on 2025-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='des',
            field=models.TextField(default=''),
        ),
    ]
