# Generated by Django 5.2.6 on 2025-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_table_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='img/')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('hobby', models.CharField(choices=[('cpp', 'Competive programming'), ('Book', 'Reading book'), ('Edu', 'Education')], default='cpp', max_length=80)),
            ],
        ),
    ]
