# Generated by Django 5.2.6 on 2025-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
