# Generated by Django 5.2.6 on 2025-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_sing_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sing_up',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
