# Generated by Django 5.2.6 on 2025-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_sing_up_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sing_up',
            name='passw',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
